### ISSUE TITLE
oadr.knob does not exist

### ISSUE THREAD

**Issue by polentino** [epri-dev/OpenADR-Virtual-Top-Node#10]
In file "documentation/1026755 OpenADR 2.0 Open Source Virtual Top Node Users Manual V3.doc" ,  paragraph `Setup the Application` of chapter `10 - Installation`, the instructions say to copy and unzip `oadr.knob` , which is not included in any of the zip files provided, nor is specified how it should be build.
It would be nice to either:
* include `oadr.knob` in the existing assets, or
* describe how to generate that file

**Comment by aru** [comment]
from my spelunking I believe oadr.knob is the old name for the entire repo, if you go to the sourceforge repos it's in there, if you unzip it it will contain all files in this repo (for ver 0.93)

hope this helps

**Comment by polentino** [comment]
thx for the tip! I moved to a different company though, so if anybody stumbles here.. I haven't verified it :)
